import { icons } from "./icons";

export const tabs = [
  { name: "index", title: "Home", icon: icons.home },
  { name: "subscriptions", title: "Subscriptions", icon: icons.wallet },
  { name: "insights", title: "Insights", icon: icons.activity },
  { name: "settings", title: "Settings", icon: icons.setting },
];

export const HOME_USER = {
  name: "Sudha Chandan Banerjee",
  designation: "Frontend Developer",
};

export const HOME_BALANCE = {
  amount: 2489.48,
  nextRenewalDate: "2026-03-18T09:00:00.000Z",
};

export const UPCOMING_SUBSCRIPTIONS: UpcomingSubscription[] = [
  {
    id: "spotify",
    icon: icons.spotify,
    name: "Spotify",
    price: 5.99,
    currency: "USD",
    daysLeft: 2,
  },
  {
    id: "notion",
    icon: icons.notion,
    name: "Notion",
    price: 12.0,
    currency: "USD",
    daysLeft: 4,
  },
  {
    id: "figma",
    icon: icons.figma,
    name: "Figma",
    price: 15.0,
    currency: "USD",
    daysLeft: 6,
  },
  {
    id: "netflixo",
    icon: icons.netflixo,
    name: "Netflix",
    price: 15.49,
    currency: "USD",
    daysLeft: 7,
  },
  {
    id: "youtube-premium",
    icon: icons.youtubePremium,
    name: "YouTube Premium",
    price: 13.99,
    currency: "USD",
    daysLeft: 8,
  },
  {
    id: "icloud",
    icon: icons.icloud,
    name: "iCloud+",
    price: 2.99,
    currency: "USD",
    daysLeft: 9,
  },
  {
    id: "googleOne",
    icon: icons.googleOne,
    name: "Google One",
    price: 1.99,
    currency: "USD",
    daysLeft: 10,
  },
  {
    id: "dropbox",
    icon: icons.dropbox,
    name: "Dropbox",
    price: 11.99,
    currency: "USD",
    daysLeft: 11,
  },
  {
    id: "slack",
    icon: icons.slack,
    name: "Slack",
    price: 8.75,
    currency: "USD",
    daysLeft: 12,
  },
  {
    id: "zoomLogo",
    icon: icons.zoomLogo,
    name: "Zoom Pro",
    price: 15.99,
    currency: "USD",
    daysLeft: 13,
  },
  {
    id: "github-pro",
    icon: icons.github,
    name: "GitHub Pro",
    price: 9.99,
    currency: "USD",
    daysLeft: 14,
  },
  {
    id: "adobe-cc",
    icon: icons.adobe,
    name: "Adobe Creative Cloud",
    price: 77.49,
    currency: "USD",
    daysLeft: 15,
  },
  {
    id: "canva-pro",
    icon: icons.canva,
    name: "Canva Pro",
    price: 12.99,
    currency: "USD",
    daysLeft: 16,
  },
  {
    id: "claude-pro",
    icon: icons.claude,
    name: "Claude Pro",
    price: 20.0,
    currency: "USD",
    daysLeft: 17,
  },
  {
    id: "chatgpt-plus",
    icon: icons.openai,
    name: "ChatGPT Plus",
    price: 20.0,
    currency: "USD",
    daysLeft: 18,
  },
  {
    id: "vercel-pro",
    icon: icons.vercel,
    name: "Vercel Pro",
    price: 20.0,
    currency: "USD",
    daysLeft: 19,
  },
  {
    id: "grammarly",
    icon: icons.grammarly,
    name: "Grammarly",
    price: 12.0,
    currency: "USD",
    daysLeft: 23,
  },
];

export const HOME_SUBSCRIPTIONS: Subscription[] = [
  {
    id: "adobe-creative-cloud",
    icon: icons.adobe,
    name: "Adobe Creative Cloud",
    plan: "Teams Plan",
    category: "Design",
    paymentMethod: "Visa ending in 8530",
    status: "active",
    startDate: "2025-03-20T10:00:00.000Z",
    price: 77.49,
    currency: "USD",
    billing: "Monthly",
    renewalDate: "2026-03-20T10:00:00.000Z",
    color: "#f5c542",
  },
  {
    id: "github-pro",
    icon: icons.github,
    name: "GitHub Pro",
    plan: "Developer",
    category: "Developer Tools",
    paymentMethod: "Mastercard ending in 2408",
    status: "active",
    startDate: "2024-11-24T10:00:00.000Z",
    price: 9.99,
    currency: "USD",
    billing: "Monthly",
    renewalDate: "2026-03-24T10:00:00.000Z",
    color: "#e8def8",
  },
  {
    id: "claude-pro",
    icon: icons.claude,
    name: "Claude Pro",
    plan: "Pro Plan",
    category: "AI Tools",
    paymentMethod: "Amex ending in 1010",
    status: "paused",
    startDate: "2025-06-27T10:00:00.000Z",
    price: 20.0,
    currency: "USD",
    billing: "Monthly",
    renewalDate: "2026-03-27T10:00:00.000Z",
    color: "#b8d4e3",
  },
  {
    id: "canva-pro",
    icon: icons.canva,
    name: "Canva Pro",
    plan: "Yearly Access",
    category: "Design",
    paymentMethod: "Visa ending in 7784",
    status: "cancelled",
    startDate: "2024-04-02T10:00:00.000Z",
    price: 119.99,
    currency: "USD",
    billing: "Yearly",
    renewalDate: "2026-04-02T10:00:00.000Z",
    color: "#b8e8d0",
  },
  {
    id: "spotify-premium",
    icon: icons.spotify,
    name: "Spotify Premium",
    plan: "Individual",
    category: "Music",
    paymentMethod: "Visa ending in 4421",
    status: "active",
    startDate: "2025-01-12T10:00:00.000Z",
    price: 5.99,
    currency: "USD",
    billing: "Monthly",
    renewalDate: "2026-03-18T10:00:00.000Z",
    color: "#c8f7c5",
  },
  {
    id: "notion-plus",
    icon: icons.notion,
    name: "Notion Plus",
    plan: "Personal Pro",
    category: "Productivity",
    paymentMethod: "Mastercard ending in 7890",
    status: "active",
    startDate: "2024-09-10T10:00:00.000Z",
    price: 12.0,
    currency: "USD",
    billing: "Monthly",
    renewalDate: "2026-03-19T10:00:00.000Z",
    color: "#f2f2f2",
  },
  {
    id: "figma-professional",
    icon: icons.figma,
    name: "Figma Professional",
    plan: "Professional",
    category: "Design",
    paymentMethod: "Visa ending in 1520",
    status: "active",
    startDate: "2025-02-05T10:00:00.000Z",
    price: 15.0,
    currency: "USD",
    billing: "Monthly",
    renewalDate: "2026-03-21T10:00:00.000Z",
    color: "#ffd6cc",
  },
  {
    id: "netflix-standard",
    icon: icons.netflixo,
    name: "Netflix",
    plan: "Standard Plan",
    category: "Entertainment",
    paymentMethod: "Amex ending in 9012",
    status: "active",
    startDate: "2024-12-01T10:00:00.000Z",
    price: 15.49,
    currency: "USD",
    billing: "Monthly",
    renewalDate: "2026-03-22T10:00:00.000Z",
    color: "#ffcdd2",
  },
  {
    id: "youtube-premium",
    icon: icons.youtubePremium,
    name: "YouTube Premium",
    plan: "Individual",
    category: "Entertainment",
    paymentMethod: "Visa ending in 6400",
    status: "active",
    startDate: "2025-04-16T10:00:00.000Z",
    price: 13.99,
    currency: "USD",
    billing: "Monthly",
    renewalDate: "2026-03-23T10:00:00.000Z",
    color: "#ffdad6",
  },
  {
    id: "icloud-plus",
    icon: icons.icloud,
    name: "iCloud+",
    plan: "200GB Storage",
    category: "Storage",
    paymentMethod: "Mastercard ending in 3124",
    status: "active",
    startDate: "2024-08-08T10:00:00.000Z",
    price: 2.99,
    currency: "USD",
    billing: "Monthly",
    renewalDate: "2026-03-25T10:00:00.000Z",
    color: "#d8ecff",
  },
  {
    id: "google-one",
    icon: icons.googleOne,
    name: "Google One",
    plan: "100GB Storage",
    category: "Storage",
    paymentMethod: "Visa ending in 1188",
    status: "active",
    startDate: "2025-05-01T10:00:00.000Z",
    price: 1.99,
    currency: "USD",
    billing: "Monthly",
    renewalDate: "2026-03-26T10:00:00.000Z",
    color: "#d7f5dd",
  },
  {
    id: "dropbox-plus",
    icon: icons.dropbox,
    name: "Dropbox Plus",
    plan: "2TB Storage",
    category: "Storage",
    paymentMethod: "Mastercard ending in 8733",
    status: "paused",
    startDate: "2025-07-11T10:00:00.000Z",
    price: 11.99,
    currency: "USD",
    billing: "Monthly",
    renewalDate: "2026-03-28T10:00:00.000Z",
    color: "#cce2ff",
  },
  {
    id: "slack-pro",
    icon: icons.slack,
    name: "Slack Pro",
    plan: "Workspace Pro",
    category: "Communication",
    paymentMethod: "Visa ending in 7055",
    status: "active",
    startDate: "2024-10-13T10:00:00.000Z",
    price: 8.75,
    currency: "USD",
    billing: "Monthly",
    renewalDate: "2026-03-29T10:00:00.000Z",
    color: "#f6d7ff",
  },
  {
    id: "zoom-pro",
    icon: icons.zoomLogo,
    name: "Zoom Pro",
    plan: "Pro Meetings",
    category: "Communication",
    paymentMethod: "Amex ending in 5591",
    status: "active",
    startDate: "2025-01-03T10:00:00.000Z",
    price: 15.99,
    currency: "USD",
    billing: "Monthly",
    renewalDate: "2026-03-30T10:00:00.000Z",
    color: "#d7e8ff",
  },
  {
    id: "chatgpt-plus",
    icon: icons.openai,
    name: "ChatGPT Plus",
    plan: "Plus Plan",
    category: "AI Tools",
    paymentMethod: "Visa ending in 4102",
    status: "active",
    startDate: "2025-08-20T10:00:00.000Z",
    price: 20.0,
    currency: "USD",
    billing: "Monthly",
    renewalDate: "2026-04-01T10:00:00.000Z",
    color: "#d6f5ea",
  },
  {
    id: "vercel-pro",
    icon: icons.vercel,
    name: "Vercel Pro",
    plan: "Pro Team",
    category: "Hosting",
    paymentMethod: "Mastercard ending in 9271",
    status: "active",
    startDate: "2025-09-14T10:00:00.000Z",
    price: 20.0,
    currency: "USD",
    billing: "Monthly",
    renewalDate: "2026-04-03T10:00:00.000Z",
    color: "#eeeeee",
  },
  {
    id: "grammarly-premium",
    icon: icons.grammarly,
    name: "Grammarly Premium",
    plan: "Premium",
    category: "Writing",
    paymentMethod: "Amex ending in 3007",
    status: "cancelled",
    startDate: "2024-03-09T10:00:00.000Z",
    price: 12.0,
    currency: "USD",
    billing: "Monthly",
    renewalDate: "2026-04-07T10:00:00.000Z",
    color: "#d2f4e8",
  },
];
